"""
<description not available>
"""

# this file was auto-generated!

from datetime import datetime, time
from numbers import Real

from openminds.base import LinkedMetadata
from openminds.properties import Property


class FunctionalMRIAcquisition(LinkedMetadata):
    """
    <description not available>
    """

    type_ = "https://openminds.om-i.org/types/FunctionalMRIAcquisition"
    context = {"@vocab": "https://openminds.om-i.org/props/"}
    schema_version = "latest"

    properties = [
        Property(
            "acquisition_duration",
            "openminds.latest.core.QuantitativeValue",
            "acquisitionDuration",
            description="no description available",
            instructions="Enter duration of volume acquisition.",
        ),
        Property(
            "behavioral_protocols",
            "openminds.latest.core.BehavioralProtocol",
            "behavioralProtocol",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all behavioral protocols that were performed during this session.",
        ),
        Property(
            "contrast_agent",
            "openminds.latest.chemicals.AmountOfChemical",
            "contrastAgent",
            description="no description available",
            instructions="Add the contrast agent used for this scan.",
        ),
        Property(
            "custom_property_sets",
            "openminds.latest.core.CustomPropertySet",
            "customPropertySet",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add any user-defined parameters grouped in context-specific sets that are not covered in the standardized properties of this activity.",
        ),
        Property(
            "delay_after_trigger",
            "openminds.latest.core.QuantitativeValue",
            "delayAfterTrigger",
            description="no description available",
            instructions="Enter the duration from trigger delivery to scan onset (only the first volume).",
        ),
        Property(
            "delay_time",
            "openminds.latest.core.QuantitativeValue",
            "delayTime",
            description="no description available",
            instructions="Enter the arbitrary delay time set by user before each volume acquisition.",
        ),
        Property(
            "description",
            str,
            "description",
            formatting="text/markdown",
            multiline=True,
            description="Longer statement or account giving the characteristics of the functional m r i acquisition.",
            instructions="Enter a description of this activity.",
        ),
        Property(
            "device",
            "openminds.latest.neuroimaging.MRIScannerUsage",
            "device",
            required=True,
            description="Piece of equipment or mechanism (hardware) designed to serve a special purpose or perform a special function.",
            instructions="Add the MRI machine setting used for this scan.",
        ),
        Property(
            "end_time",
            [datetime, time],
            "endTime",
            description="no description available",
            instructions="Enter the date and/or time on when this activity ended, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).",
        ),
        Property(
            "field_maps",
            "openminds.latest.core.File",
            "fieldMap",
            multiple=True,
            unique_items=False,
            min_items=1,
            description="no description available",
            instructions="Add the images or field maps used for correction of inhomogeneities in B0 field of this acquisition.",
        ),
        Property(
            "inputs",
            ["openminds.latest.core.SubjectState", "openminds.latest.core.TissueSampleState"],
            "input",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that is put into or participates in a process or machine.",
            instructions="Add the state of the subject or tissue sample before this session.",
        ),
        Property(
            "is_part_of",
            "openminds.latest.core.DatasetVersion",
            "isPartOf",
            required=True,
            description="Reference to the ensemble of multiple things or beings.",
            instructions="Add the dataset version in which this activity was conducted.",
        ),
        Property(
            "lookup_label",
            str,
            "lookupLabel",
            formatting="text/plain",
            description="no description available",
            instructions="Enter a lookup label for this activity that may help you to find this instance more easily.",
        ),
        Property(
            "number_of_volumes_discarded_by_user",
            Real,
            "numberOfVolumesDiscardedByUser",
            description="no description available",
            instructions="Enter number of volumes discarded by user before the first volume.",
        ),
        Property(
            "outputs",
            ["openminds.latest.core.File", "openminds.latest.core.FileBundle"],
            "output",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Something or someone that comes out of, is delivered or produced by a process or machine.",
            instructions="Add all outputs generated by this activity.",
        ),
        Property(
            "performed_by",
            ["openminds.latest.computation.SoftwareAgent", "openminds.latest.core.Person"],
            "performedBy",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all agents that performed this activity.",
        ),
        Property(
            "preparation_design",
            "openminds.latest.controlled_terms.PreparationType",
            "preparationDesign",
            description="no description available",
            instructions="Add the initial preparation type for this activity.",
        ),
        Property(
            "protocols",
            "openminds.latest.core.Protocol",
            "protocol",
            multiple=True,
            unique_items=True,
            min_items=1,
            required=True,
            description="Plan that describes the process of a scientific or medical experiment, treatment, or procedure.",
            instructions="Add all protocols used during this activity.",
        ),
        Property(
            "sbref",
            "openminds.latest.core.File",
            "sbref",
            description="no description available",
            instructions="Add the single-band reference image for this volume.",
        ),
        Property(
            "specimen_orientation",
            "openminds.latest.controlled_terms.AnatomicalAxesOrientation",
            "specimenOrientation",
            description="no description available",
            instructions="Add the anatomical orientation of the specimen in the scanner.",
        ),
        Property(
            "start_time",
            [datetime, time],
            "startTime",
            description="no description available",
            instructions="Enter the date and/or time on when this activity started, formatted as either '2023-02-07T16:00:00+00:00' (date-time) or '16:00:00+00:00' (time).",
        ),
        Property(
            "structural_mri",
            "openminds.latest.core.File",
            "structuralMRI",
            description="no description available",
            instructions="Add the structural MRI relevant for this acquisition.",
        ),
        Property(
            "study_targets",
            [
                "openminds.latest.controlled_terms.AuditoryStimulusType",
                "openminds.latest.controlled_terms.BiologicalOrder",
                "openminds.latest.controlled_terms.BiologicalSex",
                "openminds.latest.controlled_terms.BreedingType",
                "openminds.latest.controlled_terms.CellCultureType",
                "openminds.latest.controlled_terms.CellType",
                "openminds.latest.controlled_terms.Disease",
                "openminds.latest.controlled_terms.DiseaseModel",
                "openminds.latest.controlled_terms.ElectricalStimulusType",
                "openminds.latest.controlled_terms.GeneticStrainType",
                "openminds.latest.controlled_terms.GustatoryStimulusType",
                "openminds.latest.controlled_terms.Handedness",
                "openminds.latest.controlled_terms.MolecularEntity",
                "openminds.latest.controlled_terms.OlfactoryStimulusType",
                "openminds.latest.controlled_terms.OpticalStimulusType",
                "openminds.latest.controlled_terms.Organ",
                "openminds.latest.controlled_terms.OrganismSubstance",
                "openminds.latest.controlled_terms.OrganismSystem",
                "openminds.latest.controlled_terms.Species",
                "openminds.latest.controlled_terms.SubcellularEntity",
                "openminds.latest.controlled_terms.TactileStimulusType",
                "openminds.latest.controlled_terms.TermSuggestion",
                "openminds.latest.controlled_terms.TissueSampleType",
                "openminds.latest.controlled_terms.UBERONParcellation",
                "openminds.latest.controlled_terms.VisualStimulusType",
                "openminds.latest.sands.CustomAnatomicalEntity",
                "openminds.latest.sands.ParcellationEntity",
                "openminds.latest.sands.ParcellationEntityVersion",
            ],
            "studyTarget",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Structure or function that was targeted within a study.",
            instructions="Add all study targets of this activity.",
        ),
        Property(
            "volume_timing",
            "openminds.latest.core.QuantitativeValueArray",
            "volumeTiming",
            description="no description available",
            instructions="Enter acquisition times of each vloume.",
        ),
    ]

    def __init__(
        self,
        id=None,
        acquisition_duration=None,
        behavioral_protocols=None,
        contrast_agent=None,
        custom_property_sets=None,
        delay_after_trigger=None,
        delay_time=None,
        description=None,
        device=None,
        end_time=None,
        field_maps=None,
        inputs=None,
        is_part_of=None,
        lookup_label=None,
        number_of_volumes_discarded_by_user=None,
        outputs=None,
        performed_by=None,
        preparation_design=None,
        protocols=None,
        sbref=None,
        specimen_orientation=None,
        start_time=None,
        structural_mri=None,
        study_targets=None,
        volume_timing=None,
    ):
        return super().__init__(
            id=id,
            acquisition_duration=acquisition_duration,
            behavioral_protocols=behavioral_protocols,
            contrast_agent=contrast_agent,
            custom_property_sets=custom_property_sets,
            delay_after_trigger=delay_after_trigger,
            delay_time=delay_time,
            description=description,
            device=device,
            end_time=end_time,
            field_maps=field_maps,
            inputs=inputs,
            is_part_of=is_part_of,
            lookup_label=lookup_label,
            number_of_volumes_discarded_by_user=number_of_volumes_discarded_by_user,
            outputs=outputs,
            performed_by=performed_by,
            preparation_design=preparation_design,
            protocols=protocols,
            sbref=sbref,
            specimen_orientation=specimen_orientation,
            start_time=start_time,
            structural_mri=structural_mri,
            study_targets=study_targets,
            volume_timing=volume_timing,
        )
