from .comment import Comment
from .doi import DOI
from .funding import Funding
from .gridid import GRIDID
from .isbn import ISBN
from .orcid import ORCID
from .quantitative_value import QuantitativeValue
from .quantitative_value_array import QuantitativeValueArray
from .quantitative_value_range import QuantitativeValueRange
from .research_product_group import ResearchProductGroup
from .rorid import RORID
from .swhid import SWHID
from .url import URL
from .web_resource import WebResource
