"""
<description not available>
"""

# this file was auto-generated!

from datetime import date
from openminds.base import IRI

from openminds.base import LinkedMetadata
from openminds.properties import Property


class WebServiceVersion(LinkedMetadata):
    """
    <description not available>
    """

    type_ = "https://openminds.ebrains.eu/core/WebServiceVersion"
    context = {"@vocab": "https://openminds.ebrains.eu/vocab/"}
    schema_version = "v2.0"

    properties = [
        Property(
            "accessibility",
            "openminds.v2.controlled_terms.ProductAccessibility",
            "accessibility",
            required=True,
            description="Level to which something is accessible to the web service version.",
            instructions="Add the accessibility of the data for this research product version.",
        ),
        Property(
            "copyright",
            "openminds.v2.core.Copyright",
            "copyright",
            description="Exclusive and assignable legal right of an originator to reproduce, publish, sell, or distribute the matter and form of a creative work for a defined time period.",
            instructions="Enter the copyright information of this research product version.",
        ),
        Property(
            "custodians",
            ["openminds.v2.core.Consortium", "openminds.v2.core.Organization", "openminds.v2.core.Person"],
            "custodian",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="The 'custodian' is a legal person who is responsible for the content and quality of the data, metadata, and/or code of a research product.",
            instructions="Add all parties that fulfill the role of a custodian for the research product version (e.g., a research group leader or principle investigator). Custodians are typically the main contact in case of misconduct, obtain permission from the contributors to publish personal information, and maintain the content and quality of the data, metadata, and/or code of the research product version.",
        ),
        Property(
            "description",
            str,
            "description",
            formatting="text/markdown",
            multiline=True,
            description="Longer statement or account giving the characteristics of the web service version.",
            instructions="Enter a description (or abstract) of this research product version. Note that this version specific description will overwrite the description for the overarching dataset.",
        ),
        Property(
            "developers",
            ["openminds.v2.core.Consortium", "openminds.v2.core.Organization", "openminds.v2.core.Person"],
            "developer",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Legal person that creates or improves products or services (e.g., software, applications, etc.).",
            instructions="Add all parties that developed this web service version. Note that these developers will overwrite the developer list provided for the overarching web service.",
        ),
        Property(
            "full_documentation",
            [
                "openminds.v2.core.DOI",
                "openminds.v2.core.File",
                "openminds.v2.core.ISBN",
                "openminds.v2.core.WebResource",
            ],
            "fullDocumentation",
            required=True,
            description="Non-abridged instructions, comments, and information for using a particular product.",
            instructions="Add the publication or file that acts as the full documentation of this research product version.",
        ),
        Property(
            "full_name",
            str,
            "fullName",
            formatting="text/plain",
            description="Whole, non-abbreviated name of the web service version.",
            instructions="Enter a descriptive full name (or title) for this research product version. Note that this version specific full name will overwrite the full name for the overarching dataset.",
        ),
        Property(
            "funding",
            "openminds.v2.core.Funding",
            "funding",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Money provided by a legal person for a particular purpose.",
            instructions="Add all funding information of this research product version.",
        ),
        Property(
            "has_parts",
            "openminds.v2.core.SoftwareVersion",
            "hasPart",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="no description available",
            instructions="Add all software versions that are components of this web service version.",
        ),
        Property(
            "homepage",
            IRI,
            "homepage",
            description="Main website of the web service version.",
            instructions="Enter the internationalized resource identifier (IRI) to the homepage of this research product version.",
        ),
        Property(
            "how_to_cite",
            str,
            "howToCite",
            formatting="text/markdown",
            multiline=True,
            description="Preferred format for citing a particular object or legal person.",
            instructions="Enter the preferred citation text for this research product version. Leave blank if citation text can be extracted from the assigned digital identifier.",
        ),
        Property(
            "input_formats",
            "openminds.v2.core.ContentType",
            "inputFormat",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Format of data that is put into a process or machine.",
            instructions="Add all content types that can be used as input by this web service version.",
        ),
        Property(
            "is_alternative_version_of",
            "openminds.v2.core.WebServiceVersion",
            "isAlternativeVersionOf",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Reference to an original form where the essence was preserved, but presented in an alternative form.",
            instructions="Add all web service versions that can be used alternatively to this web service version.",
        ),
        Property(
            "is_new_version_of",
            "openminds.v2.core.WebServiceVersion",
            "isNewVersionOf",
            description="Reference to a previous (potentially outdated) particular form of something.",
            instructions="Add the web service version preceding this web service version.",
        ),
        Property(
            "keywords",
            [
                "openminds.v2.controlled_terms.ActionStatusType",
                "openminds.v2.controlled_terms.AgeCategory",
                "openminds.v2.controlled_terms.AnalysisTechnique",
                "openminds.v2.controlled_terms.AnatomicalAxesOrientation",
                "openminds.v2.controlled_terms.AnatomicalIdentificationType",
                "openminds.v2.controlled_terms.AnatomicalPlane",
                "openminds.v2.controlled_terms.AnnotationCriteriaType",
                "openminds.v2.controlled_terms.AnnotationType",
                "openminds.v2.controlled_terms.AtlasType",
                "openminds.v2.controlled_terms.AuditoryStimulusType",
                "openminds.v2.controlled_terms.BiologicalOrder",
                "openminds.v2.controlled_terms.BiologicalProcess",
                "openminds.v2.controlled_terms.BiologicalSex",
                "openminds.v2.controlled_terms.BreedingType",
                "openminds.v2.controlled_terms.CellCultureType",
                "openminds.v2.controlled_terms.CellType",
                "openminds.v2.controlled_terms.ChemicalMixtureType",
                "openminds.v2.controlled_terms.Colormap",
                "openminds.v2.controlled_terms.ContributionType",
                "openminds.v2.controlled_terms.CranialWindowConstructionType",
                "openminds.v2.controlled_terms.CranialWindowReinforcementType",
                "openminds.v2.controlled_terms.CriteriaQualityType",
                "openminds.v2.controlled_terms.DataType",
                "openminds.v2.controlled_terms.DeviceType",
                "openminds.v2.controlled_terms.DifferenceMeasure",
                "openminds.v2.controlled_terms.Disease",
                "openminds.v2.controlled_terms.DiseaseModel",
                "openminds.v2.controlled_terms.EducationalLevel",
                "openminds.v2.controlled_terms.ElectricalStimulusType",
                "openminds.v2.controlled_terms.EthicsAssessment",
                "openminds.v2.controlled_terms.ExperimentalApproach",
                "openminds.v2.controlled_terms.FileBundleGrouping",
                "openminds.v2.controlled_terms.FileRepositoryType",
                "openminds.v2.controlled_terms.FileUsageRole",
                "openminds.v2.controlled_terms.GeneticStrainType",
                "openminds.v2.controlled_terms.GustatoryStimulusType",
                "openminds.v2.controlled_terms.Handedness",
                "openminds.v2.controlled_terms.Language",
                "openminds.v2.controlled_terms.Laterality",
                "openminds.v2.controlled_terms.LearningResourceType",
                "openminds.v2.controlled_terms.MRIPulseSequence",
                "openminds.v2.controlled_terms.MeasuredQuantity",
                "openminds.v2.controlled_terms.MeasuredSignalType",
                "openminds.v2.controlled_terms.MetaDataModelType",
                "openminds.v2.controlled_terms.ModelAbstractionLevel",
                "openminds.v2.controlled_terms.ModelScope",
                "openminds.v2.controlled_terms.MolecularEntity",
                "openminds.v2.controlled_terms.OlfactoryStimulusType",
                "openminds.v2.controlled_terms.OperatingDevice",
                "openminds.v2.controlled_terms.OperatingSystem",
                "openminds.v2.controlled_terms.OpticalStimulusType",
                "openminds.v2.controlled_terms.Organ",
                "openminds.v2.controlled_terms.OrganismSubstance",
                "openminds.v2.controlled_terms.OrganismSystem",
                "openminds.v2.controlled_terms.PatchClampVariation",
                "openminds.v2.controlled_terms.PreparationType",
                "openminds.v2.controlled_terms.ProductAccessibility",
                "openminds.v2.controlled_terms.ProgrammingLanguage",
                "openminds.v2.controlled_terms.QualitativeOverlap",
                "openminds.v2.controlled_terms.SemanticDataType",
                "openminds.v2.controlled_terms.Service",
                "openminds.v2.controlled_terms.SetupType",
                "openminds.v2.controlled_terms.SoftwareApplicationCategory",
                "openminds.v2.controlled_terms.SoftwareFeature",
                "openminds.v2.controlled_terms.Species",
                "openminds.v2.controlled_terms.StimulationApproach",
                "openminds.v2.controlled_terms.StimulationTechnique",
                "openminds.v2.controlled_terms.SubcellularEntity",
                "openminds.v2.controlled_terms.SubjectAttribute",
                "openminds.v2.controlled_terms.TactileStimulusType",
                "openminds.v2.controlled_terms.Technique",
                "openminds.v2.controlled_terms.TermSuggestion",
                "openminds.v2.controlled_terms.Terminology",
                "openminds.v2.controlled_terms.TissueSampleAttribute",
                "openminds.v2.controlled_terms.TissueSampleType",
                "openminds.v2.controlled_terms.TypeOfUncertainty",
                "openminds.v2.controlled_terms.UBERONParcellation",
                "openminds.v2.controlled_terms.UnitOfMeasurement",
                "openminds.v2.controlled_terms.VisualStimulusType",
            ],
            "keyword",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Significant word or concept that are representative of the web service version.",
            instructions="Add all relevant keywords to this research product version either by adding controlled terms or by suggesting new terms.",
        ),
        Property(
            "other_contributions",
            "openminds.v2.core.Contribution",
            "otherContribution",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Giving or supplying of something (such as money or time) as a part or share other than what is covered elsewhere.",
            instructions="Add any other contributions to this research product version that are not covered under 'author'/'developer' or 'custodian'.",
        ),
        Property(
            "output_formats",
            "openminds.v2.core.ContentType",
            "outputFormat",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Format of data that comes out of, is delivered or produced by a process or machine.",
            instructions="Add all content types that can be generated as output by this web service version.",
        ),
        Property(
            "related_publications",
            ["openminds.v2.core.DOI", "openminds.v2.core.HANDLE", "openminds.v2.core.ISBN", "openminds.v2.core.ISSN"],
            "relatedPublication",
            multiple=True,
            unique_items=True,
            min_items=1,
            description="Reference to something that was made available for the general public to see or buy.",
            instructions="Add all further publications besides the full documentation that provide the original context for the production of this research product version (e.g., an original research article that used or produced the data of this research product version).",
        ),
        Property(
            "release_date",
            date,
            "releaseDate",
            required=True,
            description="Fixed date on which a product is due to become or was made available for the general public to see or buy",
            instructions="Enter the date (actual or intended) on which this research product version was first release, formatted as 'YYYY-MM-DD'.",
        ),
        Property(
            "repository",
            "openminds.v2.core.FileRepository",
            "repository",
            description="Place, room, or container where something is deposited or stored.",
            instructions="Add the file repository of this research product version.",
        ),
        Property(
            "short_name",
            str,
            "shortName",
            formatting="text/plain",
            required=True,
            description="Shortened or fully abbreviated name of the web service version.",
            instructions="Enter a short name (or alias) for this research product version that could be used as a shortened display title (e.g., for web services with too little space to display the full name).",
        ),
        Property(
            "support_channels",
            str,
            "supportChannel",
            multiple=True,
            unique_items=True,
            min_items=1,
            formatting="text/plain",
            description="Way of communication used to interact with users or customers.",
            instructions="Enter all channels through which a user can receive support for handling this research product version.",
        ),
        Property(
            "version_identifier",
            str,
            "versionIdentifier",
            formatting="text/plain",
            required=True,
            description="Term or code used to identify the version of something.",
            instructions="Enter the version identifier of this research product version.",
        ),
        Property(
            "version_innovation",
            str,
            "versionInnovation",
            formatting="text/markdown",
            multiline=True,
            required=True,
            description="Documentation on what changed in comparison to a previously published form of something.",
            instructions="Enter a short description (or summary) of the novelties/peculiarities of this research product version in comparison to its preceding versions. If this research product version is the first version, you can enter the following disclaimer 'This is the first version of this research product'.",
        ),
    ]

    def __init__(
        self,
        id=None,
        accessibility=None,
        copyright=None,
        custodians=None,
        description=None,
        developers=None,
        full_documentation=None,
        full_name=None,
        funding=None,
        has_parts=None,
        homepage=None,
        how_to_cite=None,
        input_formats=None,
        is_alternative_version_of=None,
        is_new_version_of=None,
        keywords=None,
        other_contributions=None,
        output_formats=None,
        related_publications=None,
        release_date=None,
        repository=None,
        short_name=None,
        support_channels=None,
        version_identifier=None,
        version_innovation=None,
    ):
        return super().__init__(
            id=id,
            accessibility=accessibility,
            copyright=copyright,
            custodians=custodians,
            description=description,
            developers=developers,
            full_documentation=full_documentation,
            full_name=full_name,
            funding=funding,
            has_parts=has_parts,
            homepage=homepage,
            how_to_cite=how_to_cite,
            input_formats=input_formats,
            is_alternative_version_of=is_alternative_version_of,
            is_new_version_of=is_new_version_of,
            keywords=keywords,
            other_contributions=other_contributions,
            output_formats=output_formats,
            related_publications=related_publications,
            release_date=release_date,
            repository=repository,
            short_name=short_name,
            support_channels=support_channels,
            version_identifier=version_identifier,
            version_innovation=version_innovation,
        )
